Moved to new graph-setup structure and added some useful docker helpers.

diff --git a/utils/configure b/utils/configure
--- a/utils/configure
+++ b/utils/configure
@@ -1,6 +1,7 @@
 #!/bin/bash
 
-base-config()
+# install required packages (ubuntu)
+install-required()
 {
     apt update && apt -y install ca-certificates curl gnupg grep apache2-utils npm
 
@@ -14,10 +15,13 @@ base-config()
         apt update && apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin docker-compose
     fi
 
-    npm install -g pino-pretty
+    if [ `npm list -g | grep -c pino-pretty` -eq 0 ]; then
+        npm install -g pino-pretty
+    fi
 }
 
-generate-node-config() 
+# generate configuration file for graph-node
+generate-node-config()
 {
 # Datbase
 cat <<EOF >$1
@@ -51,4 +55,61 @@ indexers = [ "index_node" ]
 [general]
 query = "query_node"
 EOF
+}
+
+# generate project env file
+# 1. project name
+# 2. operating network
+generate-project-env()
+{
+    # Load user configuration file
+    source .env.user
+
+    # Set project variables
+    echo "COMPOSE_PROJECT_NAME=$1" > .env.$1
+
+    # Hosts
+    echo "INDEX_HOST=index-$1.$HOST" >> .env.$1
+    echo "GRAFANA_HOST=dashboard-$1.$HOST" >> .env.$1
+    echo "PROMETHEUS_HOST=prometheus-$1.$HOST" >> .env.$1
+
+    if [ "$2" = "mainnet" ]; then
+        echo "TXN_RPC=$TXN_RPC_MAINNET" >> .env.$1
+        echo "ETHEREUM_NETWORK="mainnet"" >> .env.$1
+        echo "NETWORK_SUBGRAPH_ENDPOINT="https://api.thegraph.com/subgraphs/name/graphprotocol/graph-network-mainnet"" >> .env.$1
+        echo "DAI_CONTRACT="0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"" >> .env.$1
+        echo "COLLECT_RECEIPTS_ENDPOINT="https://gateway.network.thegraph.com/collect-receipts"" >> .env.$1
+        echo "EPOCH_SUBGRAPH_ENDPOINT="https://api.thegraph.com/subgraphs/name/graphprotocol/mainnet-epoch-block-oracle"" >> .env.$1
+        echo "CLIENT_SIGNER_ADDRESS="0x982D10c56b8BBbD6e09048F5c5f01b43C65D5aE0"" >> .env.$1
+    elif [ "$2" = "goerli" ]; then
+        echo "TXN_RPC=$TXN_RPC_GOERLI" >> .env.$1
+        echo "ETHEREUM_NETWORK="goerli"" >> .env.$1
+        echo "NETWORK_SUBGRAPH_ENDPOINT="https://api.thegraph.com/subgraphs/name/graphprotocol/graph-network-goerli"" >> .env.$1
+        echo "DAI_CONTRACT="0x9e7e607afd22906f7da6f1ec8f432d6f244278be"" >> .env.$1
+        echo "COLLECT_RECEIPTS_ENDPOINT="https://gateway.testnet.thegraph.com/collect-receipts"" >> .env.$1
+        echo "EPOCH_SUBGRAPH_ENDPOINT="https://api.thegraph.com/subgraphs/name/graphprotocol/goerli-epoch-block-oracle"" >> .env.$1
+        echo "CLIENT_SIGNER_ADDRESS="0xe1EC4339019eC9628438F8755f847e3023e4ff9c"" >> .env.$1
+    elif [ "$2" = "arbitrum-one" ]; then
+        echo "TXN_RPC=$TXN_RPC_ARBITRUM" >> .env.$1
+        echo "ETHEREUM_NETWORK="arbitrum-one"" >> .env.$1
+        echo "NETWORK_SUBGRAPH_ENDPOINT="https://api.thegraph.com/subgraphs/name/graphprotocol/graph-network-arbitrum"" >> .env.$1
+        echo "DAI_CONTRACT="0x11fE4B6AE13d2a6055C8D9cF65c55bac32B5d844"" >> .env.$1
+        echo "COLLECT_RECEIPTS_ENDPOINT="https://gateway-arbitrum.network.thegraph.com/collect-receipts"" >> .env.$1
+        echo "EPOCH_SUBGRAPH_ENDPOINT="https://api.thegraph.com/subgraphs/name/graphprotocol/arbitrum-epoch-block-oracle"" >> .env.$1
+        echo "CLIENT_SIGNER_ADDRESS="0xc483960d4D58eabc434Dc88a620AdFd883D6Dd4e"" >> .env.$1
+    elif [ "$2" = "arbitrum-goerli" ]; then
+        echo "TXN_RPC=$TXN_RPC_ARBITRUM_GOERLI" >> .env.$1
+        echo "ETHEREUM_NETWORK="goerli"" >> .env.$1
+        echo "NETWORK_SUBGRAPH_ENDPOINT="https://api.thegraph.com/subgraphs/name/graphprotocol/graph-network-arbitrum-goerli"" >> .env.$1
+        echo "DAI_CONTRACT="0x11fE4B6AE13d2a6055C8D9cF65c55bac32B5d844"" >> .env.$1
+        echo "COLLECT_RECEIPTS_ENDPOINT="https://gateway-testnet-arbitrum.network.thegraph.com/collect-receipts"" >> .env.$1
+        echo "EPOCH_SUBGRAPH_ENDPOINT="https://api.thegraph.com/subgraphs/name/graphprotocol/arb-goerli-epoch-block-oracle"" >> .env.$1
+        echo "CLIENT_SIGNER_ADDRESS="0xac01B0b3B2Dc5D8E0D484c02c4d077C15C96a7b4"" >> .env.$1
+    else
+        echo "Error: network not found." >&2
+        exit 1
+    fi
+
+    # Project configuration file
+    cat .env.user >> .env.$1
 }
diff --git a/utils/manage b/utils/manage
--- a/utils/manage
+++ b/utils/manage
@@ -1,118 +1,181 @@
-#!/bin/
+#!/bin/bash
+DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+. $DIR/docker
+. $DIR/configure
 
 graph-start() {
-    source .env.$1
-
+    source $GRAPH_DIR/.env.$1
     if $AUTOAGORA; then 
-        COMPOSE_FILE=services/graph-setup.yml:services/autoagora.yml
         COMPOSE_PROFILES=autoagora
     else
-        COMPOSE_FILE=services/graph-setup.yml
         COMPOSE_PROFILES=no-autoagora
     fi
+    export PROJECT=$COMPOSE_PROJECT_NAME
 
     case $2 in
-        "proxy")
-            COMPOSE_PROJECT_NAME=proxy COMPOSE_PROFILES=$PROXY EMAIL=email@$HOST WHITELIST=$WHITELIST docker compose -f services/reverse-proxy.yml up -d --remove-orphans --force-recreate --build
-            ;;
         "node")
-            source utils/configure
-            NODE_CONFIG_FILE=/var/lib/docker/volumes/${COMPOSE_PROJECT_NAME}_node-config/_data/config.toml
+            echo "Start graph NODE"
+            # create node configuration volume
+            if ! volume-exists ${PROJECT}_node-config; then
+                docker volume create ${PROJECT}_node-config
+            fi
+
+            # generate graph node configuration files
+            NODE_CONFIG_FILE=/var/lib/docker/volumes/${PROJECT}_node-config/_data/config.toml
             generate-node-config $NODE_CONFIG_FILE
-            COMPOSE_FILE=$COMPOSE_FILE COMPOSE_PROFILES=$COMPOSE_PROFILES docker compose --env-file .env.$1 up -d --remove-orphans --force-recreate --build index-node query-node
+
+            # start docker compose
+            COMPOSE_FILE=$GRAPH_DIR/services/node.yml \
+            COMPOSE_PROFILES=$COMPOSE_PROFILES \
+            COMPOSE_IGNORE_ORPHANS=True \
+            docker compose --env-file $GRAPH_DIR/.env.$1 up -d --force-recreate --build
+            
+            # attach graph node to local chains
             for node in "${CHAIN_NAME[@]}"
             do
             if [ $node == 'mainnet' ]; then 
                 node=ethereum 
             fi
             if [ "$(docker network ls -f name=$node -q)" ]; then
-                docker network connect $node ${COMPOSE_PROJECT_NAME}-index-node
-                docker network connect $node ${COMPOSE_PROJECT_NAME}-query-node
+                docker network connect $node ${PROJECT}-index-node
+                docker network connect $node ${PROJECT}-query-node
             fi
             done
             ;;
         "indexer")
-            COMPOSE_FILE=$COMPOSE_FILE COMPOSE_PROFILES=$COMPOSE_PROFILES docker compose --env-file .env.$1 up -d --remove-orphans --force-recreate --build indexer-agent indexer-service indexer-cli
+            echo "Starting graph INDEXER"
+            COMPOSE_FILE=$GRAPH_DIR/services/indexer.yml \
+            COMPOSE_PROFILES=$COMPOSE_PROFILES \
+            COMPOSE_IGNORE_ORPHANS=True \
+            docker compose --env-file $GRAPH_DIR/.env.$1 up -d --force-recreate --build
+
+            # cli history
+            if [ ! -f /var/lib/docker/volumes/${PROJECT}_cli-history/_data/.bash_history ]; then
+                touch /var/lib/docker/volumes/${PROJECT}_cli-history/_data/.bash_history
+            fi
             ;;
         "monitor")
-            export PROJECT=$COMPOSE_PROJECT_NAME
-            
-            # Prometheus Config
-            rm -rf /var/lib/docker/volumes/${PROJECT}_prometheus-config/_data/alert.rules /var/lib/docker/volumes/${PROJECT}_prometheus-config/_data/prometheus.yml
+            echo "Starting graph MONITOR"
+
+            # Prometheus
+            if ! volume-exists ${PROJECT}_prometheus-config; then
+                docker volume create ${PROJECT}_prometheus-config
+            else
+                rm -rf /var/lib/docker/volumes/${PROJECT}_prometheus-config/_data/alert.rules /var/lib/docker/volumes/${PROJECT}_prometheus-config/_data/prometheus.yml
+            fi
             envsubst '${PROJECT}' < prometheus/alert.rules > /var/lib/docker/volumes/${PROJECT}_prometheus-config/_data/alert.rules
             envsubst < prometheus/prometheus.yml > /var/lib/docker/volumes/${PROJECT}_prometheus-config/_data/prometheus.yml
             
-            # Grafana Config
-            rm -rf /var/lib/docker/volumes/${PROJECT}_grafana-provisioning/_data/*
+            # Grafana
+            if ! volume-exists ${PROJECT}_grafana-provisioning; then
+                docker volume create ${PROJECT}_grafana-provisioning
+            else
+                rm -rf /var/lib/docker/volumes/${PROJECT}_grafana-provisioning/_data/*
+            fi
             cp -R grafana/dashboards/ grafana/datasources/ /var/lib/docker/volumes/${PROJECT}_grafana-provisioning/_data
             envsubst < grafana/dashboards/indexing-performance-metrics.json > /var/lib/docker/volumes/${PROJECT}_grafana-provisioning/_data/dashboards/indexing-performance-metrics.json
+            
+            # Alertmanager
+            if ! volume-exists ${PROJECT}_alertmanager-config; then
+                docker volume create ${PROJECT}_alertmanager-config
+                cp alertmanager/config.yml /var/lib/docker/volumes/${PROJECT}_alertmanager-config/_data
+            fi
 
-            COMPOSE_FILE=$COMPOSE_FILE COMPOSE_PROFILES=$COMPOSE_PROFILES docker compose --env-file .env.$1 up -d --force-recreate --build grafana prometheus
-            unset PROJECT
+            COMPOSE_FILE=$GRAPH_DIR/services/monitor.yml \
+            COMPOSE_PROFILES=$COMPOSE_PROFILES \
+            COMPOSE_IGNORE_ORPHANS=True \
+            docker compose --env-file $GRAPH_DIR/.env.$1 up -d --force-recreate --build
             ;;
-        "all")
-            source utils/configure
-            NODE_CONFIG_FILE=/var/lib/docker/volumes/${COMPOSE_PROJECT_NAME}_node-config/_data/config.toml
-            generate-node-config $NODE_CONFIG_FILE
-
-            export PROJECT=$COMPOSE_PROJECT_NAME
-            
-            # Prometheus Config
-            rm -rf /var/lib/docker/volumes/${PROJECT}_prometheus-config/_data/alert.rules /var/lib/docker/volumes/${PROJECT}_prometheus-config/_data/prometheus.yml
-            envsubst '${PROJECT}' < prometheus/alert.rules > /var/lib/docker/volumes/${PROJECT}_prometheus-config/_data/alert.rules
-            envsubst < prometheus/prometheus.yml > /var/lib/docker/volumes/${PROJECT}_prometheus-config/_data/prometheus.yml
-            
-            # Grafana Config
-            rm -rf /var/lib/docker/volumes/${PROJECT}_grafana-provisioning/_data/*
-            cp -R grafana/dashboards/ grafana/datasources/ /var/lib/docker/volumes/${PROJECT}_grafana-provisioning/_data
-            envsubst < grafana/dashboards/indexing-performance-metrics.json > /var/lib/docker/volumes/${PROJECT}_grafana-provisioning/_data/dashboards/indexing-performance-metrics.json
-            
-            COMPOSE_FILE=$COMPOSE_FILE COMPOSE_PROFILES=$COMPOSE_PROFILES docker compose --env-file .env.$1 up -d --force-recreate --build
-
-            for node in "${CHAIN_NAME[@]}"
-            do
-            if [ $node == 'mainnet' ]; then 
-                node=ethereum 
-            fi
-            if [ "$(docker network ls -f name=$node -q)" ]; then
-                docker network connect $node ${COMPOSE_PROJECT_NAME}-index-node
-                docker network connect $node ${COMPOSE_PROJECT_NAME}-query-node
-            fi
-            done
+        *)
+            echo "Starting graph ALL"
+            COMPOSE_FILE=$GRAPH_DIR/services/node.yml:$GRAPH_DIR/services/indexer.yml:$GRAPH_DIR/services/monitor.yml \
+            COMPOSE_PROFILES=$COMPOSE_PROFILES \
+            docker compose --env-file $GRAPH_DIR/.env.$1 up -d --force-recreate --build
             ;;
     esac
+
+    unset PROJECT
 }
 
 graph-stop() {
-    source .env.$1
-
+    source $GRAPH_DIR/.env.$1
     if $AUTOAGORA; then 
-        COMPOSE_FILE=services/graph-setup.yml:services/autoagora.yml
         COMPOSE_PROFILES=autoagora
     else
-        COMPOSE_FILE=services/graph-setup.yml
         COMPOSE_PROFILES=no-autoagora
     fi
 
     case $2 in
         "node")
-            COMPOSE_FILE=$COMPOSE_FILE COMPOSE_PROFILES=$COMPOSE_PROFILES docker compose --env-file .env.$1 stop index-node query-node
+            echo "Stopping graph NODE"
+            COMPOSE_FILE=$GRAPH_DIR/services/node.yml docker compose --env-file $GRAPH_DIR/.env.$1 stop
             ;;
         "indexer")
-            COMPOSE_FILE=$COMPOSE_FILE COMPOSE_PROFILES=$COMPOSE_PROFILES docker compose --env-file .env.$1 stop indexer-agent indexer-cli indexer-service
+            echo "Stopping graph INDEXER"
+            COMPOSE_FILE=$GRAPH_DIR/services/indexer.yml COMPOSE_PROFILES=$COMPOSE_PROFILES docker compose --env-file $GRAPH_DIR/.env.$1 stop
             ;;
         "monitor")
-            COMPOSE_FILE=$COMPOSE_FILE COMPOSE_PROFILES=$COMPOSE_PROFILES docker compose --env-file .env.$1 stop grafana prometheus
+            echo "Stopping graph MONITOR"
+            COMPOSE_FILE=$GRAPH_DIR/services/monitor.yml docker compose --env-file $GRAPH_DIR/.env.$1 stop
+            ;;
+        *)
+            echo "Stopping graph ALL"
+            tmux kill-session -t $1
+            COMPOSE_FILE=$GRAPH_DIR/services/node.yml:$GRAPH_DIR/services/indexer.yml:$GRAPH_DIR/services/monitor.yml \
+            COMPOSE_PROFILES=$COMPOSE_PROFILES \
+            docker compose --env-file $GRAPH_DIR/.env.$1 stop
             ;;
     esac
 }
 
+graph-connect() {
+    if [ -z "$1" ] || [ -z "$2" ]; then
+        echo "Define 1. indexer name and 2. proxy service" >&2
+        exit 1
+    fi
+
+    # Attach proxy to indexer network
+    for net in $(docker container inspect --format '{{range $net,$v := .NetworkSettings.Networks}}{{printf "%s\n" $net}}{{end}}' ${2}-proxy)
+    do
+      if [ "$net" = ${1}-indexer ]; then
+        echo "Proxy already connected" >&2
+        return
+      fi
+    done
+
+    docker network connect ${1}-indexer ${2}-proxy
+}
+
+graph-disconnect() {
+    if [ -z "$1" ] || [ -z "$2" ]; then
+        echo "Define 1. indexer name and 2. proxy service" >&2
+        exit 1
+    fi
+
+    # Attach proxy to indexer network
+    for net in $(docker container inspect --format '{{range $net,$v := .NetworkSettings.Networks}}{{printf "%s\n" $net}}{{end}}' ${2}-proxy)
+    do
+      if [ "$net" = ${1}-indexer ]; then
+        docker network disconnect ${1}-indexer ${2}-proxy
+        return
+      fi
+    done
+
+    echo "Proxy not connected" >&2
+}
+
 graph-monitor() {
+    # check if container running
+    if [ -z "$( docker ps | grep $1-indexer-cli )" ]; then
+        echo "Project not found."
+        return
+    fi
+
     # Check if session name exists
     SESSIONEXISTS=$(tmux list-sessions | grep $1)
 
     # Set up monitoring interface
-    if [ "$SESSIONEXISTS" = "" ]
+    if [ "$SESSIONEXISTS" = "" ];
     then
         # Create new session
         tmux new-session -d -s $1
